export const FETCH_ALL_REQUEST = "FETCH_ALL_REQUEST";
export const FETCH_ALL_SUCCESS = "FETCH_ALL_SUCCESS";
export const FETCH_ALL_FAILURE = "FETCH_ALL_FAILURE";
export const FETCH_DATA_BY_TYPE_REQUEST = "FETCH_DATA_BY_TYPE_REQUEST";
export const FETCH_DATA_BY_TYPE_SUCCESS = "FETCH_DATA_BY_TYPE_SUCCESS";
export const FETCH_DATA_BY_TYPE_FAILURE = "FETCH_DATA_BY_TYPE_FAILURE"; 
